-- Execute this script in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'client',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create News Table
CREATE TABLE IF NOT EXISTS news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    media_filename TEXT,
    media_type TEXT DEFAULT 'none',
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create initial Admin Account (Password: admin123)
-- bcrypt hash for 'admin123'
INSERT INTO users (username, email, password, role)
VALUES ('admin', 'admin@news.com', '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW', 'admin')
ON CONFLICT (email) DO NOTHING;

-- 4. Enable Row Level Security (RLS) policies or allow public access for PostgREST if required
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE news ENABLE ROW LEVEL SECURITY;

-- Simple policies for anon key / service key access if RLS is enabled:
CREATE POLICY "Allow public read/write users" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write news" ON news FOR ALL USING (true) WITH CHECK (true);
